In [ ]:
import pyarrow.parquet as pq
import pandas as pd

In [4]:
#read in data
files = ['yellow_tripdata_2025-06.parquet', 'yellow_tripdata_2025-07.parquet']

tables = [pq.read_table(f).to_pandas() for f in files]
df = pd.concat(tables, ignore_index=True)
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 8221923 entries, 0 to 8221922
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     str
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
dtypes: datetime64[us](2), float64(13), int32(3), int64(1), str(1)
memory usage: 1.1 GB
None

In [5]:
print("Head:")
df.head(10)

Head:

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-06-01 00:02:50,2025-06-01 00:39:51,1.0,10.00,1.0,N,138,50,1,47.8,11.00,0.5,20.15,6.94,1.0,87.39,2.5,1.75,0.75
1,2,2025-06-01 00:11:27,2025-06-01 00:35:35,1.0,3.93,1.0,N,158,237,1,24.7,1.00,0.5,6.09,0.00,1.0,36.54,2.5,0.00,0.75
2,1,2025-06-01 00:43:47,2025-06-01 00:49:16,0.0,0.70,1.0,N,230,163,1,7.2,4.25,0.5,2.59,0.00,1.0,15.54,2.5,0.00,0.75
3,1,2025-06-01 00:01:15,2025-06-01 00:42:16,1.0,17.00,2.0,N,132,232,1,70.0,3.25,0.5,5.00,0.00,1.0,79.75,2.5,0.00,0.75
4,7,2025-06-01 00:16:32,2025-06-01 00:16:32,1.0,2.22,1.0,N,48,234,1,20.5,0.00,0.5,5.25,0.00,1.0,31.50,2.5,0.00,0.75
5,1,2025-06-01 00:05:23,2025-06-01 00:16:57,0.0,0.90,1.0,N,164,90,2,11.4,4.25,0.5,0.00,0.00,1.0,17.15,2.5,0.00,0.75
6,1,2025-06-01 00:23:04,2025-06-01 00:35:25,0.0,1.90,1.0,N,246,113,1,12.8,4.25,0.5,3.70,0.00,1.0,22.25,2.5,0.00,0.75
7,1,2025-06-01 00:37:37,2025-06-01 00:42:28,0.0,0.70,1.0,N,113,113,1,7.2,4.25,0.5,2.55,0.00,1.0,15.50,2.5,0.00,0.75
8,1,2025-06-01 00:44:28,2025-06-01 00:50:01,0.0,0.50,1.0,N,249,249,1,7.2,4.25,0.5,2.55,0.00,1.0,15.50,2.5,0.00,0.75
9,1,2025-06-01 00:52:28,2025-06-01 01:03:29,1.0,2.50,1.0,N,249,142,1,13.5,4.25,0.5,5.75,0.00,1.0,25.00,2.5,0.00,0.75

In [6]:
print("Missing Values:")
df.isna().sum()

Missing Values:

VendorID                       0
tpep_pickup_datetime           0
tpep_dropoff_datetime          0
passenger_count          2251701
trip_distance                  0
RatecodeID               2251701
store_and_fwd_flag       2251701
PULocationID                   0
DOLocationID                   0
payment_type                   0
fare_amount                    0
extra                          0
mta_tax                        0
tip_amount                     0
tolls_amount                   0
improvement_surcharge          0
total_amount                   0
congestion_surcharge     2251701
Airport_fee              2251701
cbd_congestion_fee             0
dtype: int64

In [7]:
print("dropoff before pickup:", len(df[df["tpep_dropoff_datetime"] < df["tpep_pickup_datetime"]]))
print("negative fare amount length:", len(df[df["fare_amount"]<0]))
print("flex fare (1), no charge (3), disputed (4), unknown (5), and voided charges (6)")
df[(df["payment_type"]!=1) & (df["payment_type"]!=2)].head(10)

dropoff before pickup: 232
negative fare amount length: 522653
flex fare (1), no charge (3), disputed (4), unknown (5), and voided charges (6)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
39,1,2025-06-01 00:38:55,2025-06-01 00:39:19,0.0,2.50,1.0,N,239,239,3,3.0,3.5,0.5,0.0,0.0,1.0,8.00,2.5,0.0,0.00
80,2,2025-06-01 00:49:34,2025-06-01 00:50:44,1.0,0.14,1.0,N,68,68,4,-3.7,-1.0,-0.5,0.0,0.0,-1.0,-9.45,-2.5,0.0,-0.75
81,2,2025-06-01 00:49:34,2025-06-01 00:50:44,1.0,0.14,1.0,N,68,68,4,3.7,1.0,0.5,0.0,0.0,1.0,9.45,2.5,0.0,0.75
224,2,2025-06-01 00:39:48,2025-06-01 00:44:40,4.0,0.83,1.0,N,100,170,4,-7.2,-1.0,-0.5,0.0,0.0,-1.0,-12.95,-2.5,0.0,-0.75
225,2,2025-06-01 00:39:48,2025-06-01 00:44:40,4.0,0.83,1.0,N,100,162,4,7.2,1.0,0.5,0.0,0.0,1.0,12.95,2.5,0.0,0.75
229,7,2025-06-01 00:31:42,2025-06-01 00:31:42,1.0,0.60,1.0,N,186,230,4,7.9,0.0,0.5,0.0,0.0,1.0,13.65,2.5,0.0,0.75
331,2,2025-06-01 00:18:11,2025-06-01 00:18:21,1.0,0.02,1.0,N,113,113,4,-3.0,-1.0,-0.5,0.0,0.0,-1.0,-8.75,-2.5,0.0,-0.75
332,2,2025-06-01 00:18:11,2025-06-01 00:18:21,1.0,0.02,1.0,N,113,113,4,3.0,1.0,0.5,0.0,0.0,1.0,8.75,2.5,0.0,0.75
458,2,2025-06-01 00:28:48,2025-06-01 00:43:28,1.0,3.17,1.0,N,142,75,4,-17.7,-1.0,-0.5,0.0,0.0,-1.0,-22.70,-2.5,0.0,0.00
459,2,2025-06-01 00:28:48,2025-06-01 00:43:28,1.0,3.17,1.0,N,142,75,4,17.7,1.0,0.5,0.0,0.0,1.0,22.70,2.5,0.0,0.00

In [8]:
print("Difference in amounts <= 100 and greater than 100")
len(df[df["total_amount"]<=100]) - len(df[df["total_amount"]>100])

Difference in amounts <= 100 and greater than 100

7982905